In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('raw-data/13F_ARK_Raw.csv')
df.head()

,Sym,Issuer Name,Cl,CUSIP,Value ($000),%,Shares,Principal,Option Type
0,TSLA,Tesla Inc,COMMON STOCK,88160R101,"1,052,546",8.2%,"2,831,329",NaN,NaN
1,AMD,Advanced Micro Devices Inc,COMMON STOCK,7903107,"551,875",4.3%,"2,712,854",NaN,NaN
2,CRSP,CRISPR Therapeutics AG,COMMON STOCK,H17182108,"538,189",4.2%,"11,313,623",NaN,NaN
3,SHOP,Shopify Inc,COMMON STOCK,82509L107,"495,553",3.9%,"4,177,652",NaN,NaN
4,PLTR,Palantir Technologies Inc,COMMON STOCK,69608A108,"454,913",3.5%,"3,109,881",NaN,NaN

In [3]:
print(df.columns.tolist())
df = df[['Sym',"Issuer Name", "Cl", '%']]
df.head()

['Sym', 'Issuer Name', 'Cl', 'CUSIP', 'Value ($000)', '%', 'Shares', 'Principal', 'Option Type']

    Sym                 Issuer Name            Cl     %
0  TSLA                   Tesla Inc  COMMON STOCK  8.2%
1   AMD  Advanced Micro Devices Inc  COMMON STOCK  4.3%
2  CRSP      CRISPR Therapeutics AG  COMMON STOCK  4.2%
3  SHOP                 Shopify Inc  COMMON STOCK  3.9%
4  PLTR   Palantir Technologies Inc  COMMON STOCK  3.5%

In [4]:
def common_stock_filter(df):
    return df[df['Cl']== 'COMMON STOCK']
df_common = common_stock_filter(df)
df_common

      Sym                 Issuer Name            Cl     %
0    TSLA                   Tesla Inc  COMMON STOCK  8.2%
1     AMD  Advanced Micro Devices Inc  COMMON STOCK  4.3%
2    CRSP      CRISPR Therapeutics AG  COMMON STOCK  4.2%
3    SHOP                 Shopify Inc  COMMON STOCK  3.9%
4    PLTR   Palantir Technologies Inc  COMMON STOCK  3.5%
..    ...                         ...           ...   ...
173   KMT              Kennametal Inc  COMMON STOCK  0.0%
175  AVNT                 Avient Corp  COMMON STOCK  0.0%
176  MTRN               Materion Corp  COMMON STOCK  0.0%
177   MMM                       3M Co  COMMON STOCK  0.0%
179   AXL           Dauch Corporation  COMMON STOCK  0.0%

[158 rows x 4 columns]

In [5]:
import yfinance as yf
from pykrx import stock
from tqdm import tqdm

KRX 로그인 실패: KRX_ID 또는 KRX_PW 환경 변수가 설정되지 않았습니다.

In [6]:
def get_fundamentals(ticker):
    try:
        info = yf.Ticker(ticker).info
        return {
            'Sym':          ticker,
            'rev_growth':   info.get('revenueGrowth'),
            'gross_margin': info.get('grossMargins'),
            'ps_ratio':     info.get('priceToSalesTrailing12Months'),
            'market_cap':   info.get('marketCap'),
            'sector':       info.get('sector'),
            'per':          info.get('trailingPE'),
            'pbr':          info.get('priceToBook'),
        }
    except Exception as e:
        print(ticker, e)
        return None

records = [get_fundamentals(t) for t in tqdm(df_common['Sym'])]
fundamentals = pd.DataFrame([r for r in records if r])

ark_enriched = df_common.merge(fundamentals, on='Sym').dropna()

  0%|          | 0/158 [00:00<?, ?it/s]

  1%|          | 1/158 [00:00<02:28,  1.06it/s]

  1%|▏         | 2/158 [00:01<01:46,  1.47it/s]

  2%|▏         | 3/158 [00:01<01:28,  1.76it/s]

  3%|▎         | 4/158 [00:02<01:15,  2.03it/s]

  3%|▎         | 5/158 [00:02<01:08,  2.24it/s]

  4%|▍         | 6/158 [00:02<01:04,  2.36it/s]

  4%|▍         | 7/158 [00:03<01:01,  2.45it/s]

  5%|▌         | 8/158 [00:03<00:59,  2.52it/s]

  6%|▌         | 9/158 [00:04<00:58,  2.55it/s]

  6%|▋         | 10/158 [00:04<00:57,  2.56it/s]

  7%|▋         | 11/158 [00:05<01:03,  2.32it/s]

  8%|▊         | 12/158 [00:05<00:59,  2.44it/s]

  8%|▊         | 13/158 [00:05<00:57,  2.51it/s]

  9%|▉         | 14/158 [00:06<01:03,  2.28it/s]

  9%|▉         | 15/158 [00:06<00:59,  2.38it/s]

 10%|█         | 16/158 [00:07<00:59,  2.40it/s]

 11%|█         | 17/158 [00:07<00:56,  2.49it/s]

 11%|█▏        | 18/158 [00:07<00:55,  2.53it/s]

 12%|█▏        | 19/158 [00:08<00:58,  2.36it/s]

 13%|█▎        | 20/158 [00:08<00:55,  2.46it/s]

 13%|█▎        | 21/158 [00:09<00:54,  2.52it/s]

 14%|█▍        | 22/158 [00:09<00:52,  2.58it/s]

 15%|█▍        | 23/158 [00:09<00:52,  2.56it/s]

 15%|█▌        | 24/158 [00:10<00:57,  2.31it/s]

 16%|█▌        | 25/158 [00:10<00:55,  2.41it/s]

 16%|█▋        | 26/158 [00:11<00:58,  2.24it/s]

 17%|█▋        | 27/158 [00:11<00:57,  2.26it/s]

 18%|█▊        | 28/158 [00:12<00:54,  2.39it/s]

 18%|█▊        | 29/158 [00:12<00:52,  2.47it/s]

 19%|█▉        | 30/158 [00:12<00:50,  2.52it/s]

 20%|█▉        | 31/158 [00:13<00:49,  2.57it/s]

 20%|██        | 32/158 [00:13<00:48,  2.61it/s]

 21%|██        | 33/158 [00:13<00:47,  2.64it/s]

 22%|██▏       | 34/158 [00:14<00:46,  2.65it/s]

 22%|██▏       | 35/158 [00:14<00:46,  2.65it/s]

 23%|██▎       | 36/158 [00:15<00:45,  2.65it/s]

 23%|██▎       | 37/158 [00:15<00:45,  2.63it/s]

 24%|██▍       | 38/158 [00:15<00:45,  2.64it/s]

 25%|██▍       | 39/158 [00:16<00:51,  2.31it/s]

 25%|██▌       | 40/158 [00:16<00:49,  2.41it/s]

 26%|██▌       | 41/158 [00:17<00:47,  2.48it/s]

 27%|██▋       | 42/158 [00:17<00:45,  2.53it/s]

 27%|██▋       | 43/158 [00:18<00:53,  2.17it/s]

 28%|██▊       | 44/158 [00:18<00:50,  2.24it/s]

 28%|██▊       | 45/158 [00:18<00:48,  2.35it/s]

 29%|██▉       | 46/158 [00:19<00:46,  2.43it/s]

 30%|██▉       | 47/158 [00:19<00:45,  2.47it/s]

 30%|███       | 48/158 [00:20<00:43,  2.53it/s]

 31%|███       | 49/158 [00:20<00:42,  2.58it/s]

 32%|███▏      | 50/158 [00:20<00:44,  2.43it/s]

 32%|███▏      | 51/158 [00:21<00:42,  2.51it/s]

 33%|███▎      | 52/158 [00:21<00:41,  2.55it/s]

 34%|███▎      | 53/158 [00:22<00:42,  2.50it/s]

 34%|███▍      | 54/158 [00:22<00:40,  2.55it/s]

 35%|███▍      | 55/158 [00:22<00:39,  2.58it/s]

 35%|███▌      | 56/158 [00:23<00:44,  2.30it/s]

 36%|███▌      | 57/158 [00:23<00:42,  2.40it/s]

 37%|███▋      | 58/158 [00:24<00:40,  2.48it/s]

 37%|███▋      | 59/158 [00:24<00:45,  2.18it/s]

 38%|███▊      | 60/158 [00:25<00:42,  2.30it/s]

 39%|███▊      | 61/158 [00:25<00:40,  2.41it/s]

 39%|███▉      | 62/158 [00:25<00:38,  2.50it/s]

 40%|███▉      | 63/158 [00:26<00:37,  2.54it/s]

 41%|████      | 64/158 [00:26<00:36,  2.58it/s]

 41%|████      | 65/158 [00:26<00:35,  2.61it/s]

 42%|████▏     | 66/158 [00:27<00:37,  2.44it/s]

 42%|████▏     | 67/158 [00:27<00:39,  2.32it/s]

 43%|████▎     | 68/158 [00:28<00:40,  2.24it/s]

 44%|████▎     | 69/158 [00:28<00:40,  2.19it/s]

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PSTG"}}}

 44%|████▍     | 70/158 [00:29<00:54,  1.62it/s]

 45%|████▍     | 71/158 [00:30<00:47,  1.84it/s]

 46%|████▌     | 72/158 [00:30<00:42,  2.04it/s]

 46%|████▌     | 73/158 [00:30<00:38,  2.19it/s]

 47%|████▋     | 74/158 [00:31<00:36,  2.32it/s]

 47%|████▋     | 75/158 [00:31<00:34,  2.41it/s]

 48%|████▊     | 76/158 [00:32<00:33,  2.48it/s]

 49%|████▊     | 77/158 [00:32<00:33,  2.44it/s]

 49%|████▉     | 78/158 [00:32<00:32,  2.47it/s]

 50%|█████     | 79/158 [00:33<00:31,  2.53it/s]

 51%|█████     | 80/158 [00:33<00:30,  2.58it/s]

 51%|█████▏    | 81/158 [00:33<00:29,  2.59it/s]

 52%|█████▏    | 82/158 [00:34<00:29,  2.62it/s]

 53%|█████▎    | 83/158 [00:34<00:28,  2.63it/s]

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: THAR"}}}

 53%|█████▎    | 84/158 [00:35<00:46,  1.58it/s]

 54%|█████▍    | 85/158 [00:36<00:42,  1.72it/s]

 54%|█████▍    | 86/158 [00:36<00:39,  1.82it/s]

 55%|█████▌    | 87/158 [00:37<00:35,  2.00it/s]

 56%|█████▌    | 88/158 [00:37<00:36,  1.90it/s]

 56%|█████▋    | 89/158 [00:38<00:33,  2.08it/s]

 57%|█████▋    | 90/158 [00:38<00:30,  2.23it/s]

 58%|█████▊    | 91/158 [00:38<00:28,  2.35it/s]

 58%|█████▊    | 92/158 [00:39<00:27,  2.44it/s]

 59%|█████▉    | 93/158 [00:39<00:26,  2.49it/s]

 59%|█████▉    | 94/158 [00:40<00:25,  2.55it/s]

 60%|██████    | 95/158 [00:40<00:24,  2.58it/s]

 61%|██████    | 96/158 [00:40<00:23,  2.60it/s]

 61%|██████▏   | 97/158 [00:41<00:23,  2.62it/s]

 62%|██████▏   | 98/158 [00:41<00:22,  2.64it/s]

 63%|██████▎   | 99/158 [00:42<00:23,  2.46it/s]

 63%|██████▎   | 100/158 [00:42<00:22,  2.53it/s]

 64%|██████▍   | 101/158 [00:42<00:23,  2.39it/s]

 65%|██████▍   | 102/158 [00:43<00:22,  2.47it/s]

 65%|██████▌   | 103/158 [00:43<00:23,  2.37it/s]

 66%|██████▌   | 104/158 [00:44<00:22,  2.45it/s]

 66%|██████▋   | 105/158 [00:44<00:21,  2.52it/s]

 67%|██████▋   | 106/158 [00:45<00:22,  2.29it/s]

 68%|██████▊   | 107/158 [00:45<00:21,  2.39it/s]

 68%|██████▊   | 108/158 [00:45<00:20,  2.47it/s]

 69%|██████▉   | 109/158 [00:46<00:19,  2.53it/s]

 70%|██████▉   | 110/158 [00:46<00:18,  2.57it/s]

 70%|███████   | 111/158 [00:46<00:18,  2.58it/s]

 71%|███████   | 112/158 [00:47<00:17,  2.60it/s]

 72%|███████▏  | 113/158 [00:47<00:17,  2.62it/s]

 72%|███████▏  | 114/158 [00:48<00:16,  2.65it/s]

 73%|███████▎  | 115/158 [00:48<00:18,  2.35it/s]

 73%|███████▎  | 116/158 [00:48<00:17,  2.42it/s]

 74%|███████▍  | 117/158 [00:49<00:16,  2.50it/s]

 75%|███████▍  | 118/158 [00:49<00:17,  2.28it/s]

 75%|███████▌  | 119/158 [00:50<00:16,  2.38it/s]

 76%|███████▌  | 120/158 [00:50<00:18,  2.08it/s]

 77%|███████▋  | 121/158 [00:51<00:16,  2.23it/s]

 77%|███████▋  | 122/158 [00:51<00:16,  2.20it/s]

 78%|███████▊  | 123/158 [00:52<00:16,  2.08it/s]

 78%|███████▊  | 124/158 [00:52<00:15,  2.22it/s]

 79%|███████▉  | 125/158 [00:52<00:14,  2.35it/s]

 80%|███████▉  | 126/158 [00:53<00:14,  2.20it/s]

 80%|████████  | 127/158 [00:53<00:13,  2.33it/s]

 81%|████████  | 128/158 [00:54<00:12,  2.43it/s]

 82%|████████▏ | 129/158 [00:54<00:12,  2.25it/s]

 82%|████████▏ | 130/158 [00:55<00:11,  2.38it/s]

 83%|████████▎ | 131/158 [00:55<00:10,  2.46it/s]

 84%|████████▎ | 132/158 [00:55<00:10,  2.51it/s]

 84%|████████▍ | 133/158 [00:56<00:09,  2.56it/s]

 85%|████████▍ | 134/158 [00:56<00:09,  2.51it/s]

 85%|████████▌ | 135/158 [00:57<00:08,  2.57it/s]

 86%|████████▌ | 136/158 [00:57<00:09,  2.33it/s]

 87%|████████▋ | 137/158 [00:58<00:10,  2.00it/s]

 87%|████████▋ | 138/158 [00:58<00:09,  2.13it/s]

 88%|████████▊ | 139/158 [00:59<00:08,  2.22it/s]

 89%|████████▊ | 140/158 [00:59<00:07,  2.34it/s]

 89%|████████▉ | 141/158 [00:59<00:06,  2.45it/s]

 90%|████████▉ | 142/158 [01:00<00:06,  2.45it/s]

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: VLDXD"}}}

 91%|█████████ | 143/158 [01:01<00:08,  1.78it/s]

 91%|█████████ | 144/158 [01:01<00:07,  1.98it/s]

 92%|█████████▏| 145/158 [01:01<00:06,  2.15it/s]

 92%|█████████▏| 146/158 [01:02<00:05,  2.28it/s]

 93%|█████████▎| 147/158 [01:02<00:04,  2.38it/s]

 94%|█████████▎| 148/158 [01:03<00:04,  2.02it/s]

 94%|█████████▍| 149/158 [01:03<00:04,  2.06it/s]

 95%|█████████▍| 150/158 [01:04<00:03,  2.22it/s]

 96%|█████████▌| 151/158 [01:04<00:02,  2.35it/s]

 96%|█████████▌| 152/158 [01:04<00:02,  2.42it/s]

 97%|█████████▋| 153/158 [01:05<00:02,  2.50it/s]

 97%|█████████▋| 154/158 [01:05<00:01,  2.51it/s]

 98%|█████████▊| 155/158 [01:05<00:01,  2.57it/s]

 99%|█████████▊| 156/158 [01:06<00:00,  2.61it/s]

 99%|█████████▉| 157/158 [01:06<00:00,  2.64it/s]

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AXL"}}}

100%|██████████| 158/158 [01:07<00:00,  1.83it/s]

100%|██████████| 158/158 [01:07<00:00,  2.34it/s]

In [7]:
ark_enriched.to_csv('raw-data/ark_enriched.csv', index=False)
print(f"Exported {len(ark_enriched)} rows with columns: {ark_enriched.columns.tolist()}")

Exported 88 rows with columns: ['Sym', 'Issuer Name', 'Cl', '%', 'rev_growth', 'gross_margin', 'ps_ratio', 'market_cap', 'sector', 'per', 'pbr']

In [8]:
ark_enriched

,Sym,Issuer Name,Cl,%,rev_growth,gross_margin,ps_ratio,market_cap,sector,per,pbr
0,TSLA,Tesla Inc,COMMON STOCK,8.2%,0.158,0.19065,16.138880,1.579657e+12,Consumer Cyclical,385.871550,19.208110
1,AMD,Advanced Micro Devices Inc,COMMON STOCK,4.3%,0.378,0.53060,25.290546,9.472321e+11,Technology,192.354300,14.689103
3,SHOP,Shopify Inc,COMMON STOCK,3.9%,0.343,0.47970,11.981741,1.481662e+11,Technology,111.941180,11.881374
4,PLTR,Palantir Technologies Inc,COMMON STOCK,3.5%,0.847,0.84074,53.538486,2.796944e+11,Technology,131.089890,33.097870
7,HOOD,Robinhood Markets Inc,COMMON STOCK,3.2%,0.151,0.92239,19.575687,9.030265e+10,Financial Services,48.679610,9.698259
...,...,...,...,...,...,...,...,...,...,...,...
152,JBL,Jabil Inc,COMMON STOCK,0.0%,0.118,0.09226,1.210752,4.066915e+10,Technology,48.305767,30.681313
153,KMT,Kennametal Inc,COMMON STOCK,0.0%,0.218,0.32078,1.250234,2.671164e+09,Industrials,19.691011,1.971649
154,AVNT,Avient Corp,COMMON STOCK,0.0%,0.025,0.32508,1.033102,3.389608e+09,Basic Materials,21.488370,1.408912
155,MTRN,Materion Corp,COMMON STOCK,0.0%,0.308,0.16403,3.228607,6.186153e+09,Basic Materials,81.254100,6.464297
156,MMM,3M Co,COMMON STOCK,0.0%,0.013,0.39714,3.374639,8.444696e+10,Industrials,31.136540,25.880754